/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ResponsableZone;

import Util.AutorisationPermModel;
import Util.AutorisationTempModel;
import Util.UserTableModel;
import java.awt.Point;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.TableRowSorter;
import modEntreesSortiesZones.AutorisationExistante;
import modEntreesSortiesZones.AutorisationPerm;
import modEntreesSortiesZones.AutorisationTemp;
import modEntreesSortiesZones.ServiceAutorisation;
import modEntreesSortiesZones.Utilisateur;

/**
 *
 * @author Fabien
 */
public class FenGestionRespZone extends javax.swing.JFrame {
    private final ServiceAutorisation monServAuto;
    private final int idZone;
    /**
     * Creates new form FenGestion
     * @param servAuto
     */

    /**
     * Creates new form FenGestion
     * @param servAuto
     * @param idZ
     */
    public FenGestionRespZone(ServiceAutorisation servAuto, int idZ) {
        initComponents();
        monServAuto = servAuto;
        idZone =idZ;
        //Récupération des autorisation
        AutorisationPerm[] lesAutorisationPerm = monServAuto.getAutorisationPerm();
        AutorisationTemp[] lesAutorisationTemp = monServAuto.getAutorisationTemp();
        //Remplissage et flitrage des tableau
        if(lesAutorisationPerm.length >0)
        {
            AutorisationPermModel modelAutorisationPerm = new AutorisationPermModel(lesAutorisationPerm);
            jTablePerm.setModel(modelAutorisationPerm);
            TableRowSorter<AutorisationPermModel> sorter = new TableRowSorter<>(modelAutorisationPerm);
            jTablePerm.setRowSorter(sorter);
        }
        if(lesAutorisationTemp.length >0)
        {
            AutorisationTempModel modelAutorisationTemp = new AutorisationTempModel(lesAutorisationTemp);
            jTableTemp.setModel(modelAutorisationTemp);
            TableRowSorter<AutorisationTempModel> sorterTemp = new TableRowSorter<>(modelAutorisationTemp);
            jTablePerm.setRowSorter(sorterTemp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMatriculeAjout = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jDateDebut = new org.jdesktop.swingx.JXDatePicker();
        jDateFin = new org.jdesktop.swingx.JXDatePicker();
        jHrsDebut = new javax.swing.JFormattedTextField();
        jHrsFin = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNomModif = new javax.swing.JTextField();
        jTextFieldPrenomModif = new javax.swing.JTextField();
        jTextFieldPhotoModif = new javax.swing.JTextField();
        jButtonModifier = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabelMatriculeModif = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTemp = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePerm = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logiciel RH");
        setResizable(false);

        jTabbedPane1.setToolTipText("Ajouter collaborateur permanent");
        jTabbedPane1.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabel1.setText("Matricule : ");

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabel2.setText("Heure début");

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabel3.setText("Heure fin");

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabel4.setText("Date début");

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabel5.setText("Date fin");

        jButtonAjouter.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setText("Nouvelle autorisation");

        try {
            jHrsDebut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jHrsFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jTextFieldMatriculeAjout)
                            .addComponent(jDateDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jHrsDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHrsFin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldMatriculeAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jHrsDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jHrsFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jTabbedPane1.addTab("Ajouter autorisation", jPanel1);

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabel6.setText("Matricule : ");

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabel7.setText("Nom : ");

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabel8.setText("Prénom : ");

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabel9.setText("Photo : ");

        jButtonModifier.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setText("Modifier un collaborateur permanent");

        jLabelMatriculeModif.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonModifier, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jTextFieldNomModif)
                            .addComponent(jTextFieldPrenomModif)
                            .addComponent(jTextFieldPhotoModif)
                            .addComponent(jLabelMatriculeModif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelMatriculeModif, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNomModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPrenomModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPhotoModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        jTabbedPane1.addTab("Modifier autorisation", jPanel2);

        jTableTemp.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jTableTemp.setToolTipText("");
        jTableTemp.setFillsViewportHeight(true);
        jTableTemp.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableTemp.setShowHorizontalLines(false);
        jTableTemp.setShowVerticalLines(false);
        jTableTemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTempMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTemp);

        jTablePerm.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jTablePerm.setToolTipText("");
        jTablePerm.setFillsViewportHeight(true);
        jTablePerm.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTablePerm.setShowHorizontalLines(false);
        jTablePerm.setShowVerticalLines(false);
        jTablePerm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePermMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePerm);

        jLabel10.setText("Autorisations permanentes");

        jLabel13.setText("Autorisations temporaires");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(471, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(249, Short.MAX_VALUE)))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Modifier collaborateur permanent");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("Modifier collaborateur permanent");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTempMouseClicked
        JTable table =(JTable) evt.getSource();
        Point p = evt.getPoint();
        int row = table.rowAtPoint(p);
        //On vérifie qu'on a bien double-cliqué sur une ligne de contenu
        if (evt.getClickCount() == 2 && row != -1) {
            UserTableModel modelCollabPerm = (UserTableModel) table.getModel();
            Utilisateur usrTemp = modelCollabPerm.getUserAt(row);
            //Remplissage des champs de modification d'un collab :
            jLabelMatriculeModif.setText(usrTemp.matricule);
            jTextFieldNomModif.setText(usrTemp.nomUsr);
            jTextFieldPrenomModif.setText(usrTemp.preUsr);
            jTextFieldPhotoModif.setText(usrTemp.phoUsr);
        }
    }//GEN-LAST:event_jTableTempMouseClicked

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        /*String matricule = jLabelMatriculeModif.getText();
        String nomUsr = jTextFieldNomModif.getText();
        String prenomUsr = jTextFieldPrenomModif.getText();
        String photoUsr = jTextFieldPhotoModif.getText();
        if(matricule != null && !matricule.isEmpty()) {
            try {
                monServAuth.modifierCollaborateurPerm(matricule, nomUsr, prenomUsr, photoUsr);
                Utilisateur newUsr = new Utilisateur(matricule, nomUsr, prenomUsr, photoUsr);
                UserTableModel modelCollabPerm = (UserTableModel) jTableCollab.getModel();
                modelCollabPerm.majAffichage(newUsr);
            } catch (UtilisateurInconnu ex) {
                Logger.getLogger(FenGestionRespZone.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
        
    }//GEN-LAST:event_jButtonModifierActionPerformed
    
    private String setDateFormatFR(Date date, int hrs, int min)
    {
        DateFormat formatFR = new SimpleDateFormat("MM/dd/yyyy HH:mm");         
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        cal.set(Calendar.HOUR_OF_DAY,hrs);
        cal.set(Calendar.MINUTE,min);
        cal.set(Calendar.SECOND,0);
        cal.set(Calendar.MILLISECOND,0);
        return formatFR.format(cal.getTime());
    }
    
    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        try{
            String matricule = jTextFieldMatriculeAjout.getText();
            String[] tabHrsDebut=jHrsDebut.getText().split(":");
            String[] tabHrsFin=jHrsFin.getText().split(":");
             
            //ajout d'une autorisation temporaire
            if(jDateDebut.getDate()!=null && jDateFin.getDate()!=null)
            {
                String dateDebut = setDateFormatFR(jDateDebut.getDate(), Integer.parseInt(tabHrsDebut[0]), Integer.parseInt(tabHrsDebut[1]));
                String dateFin = setDateFormatFR(jDateFin.getDate(), Integer.parseInt(tabHrsFin[0]), Integer.parseInt(tabHrsFin[1]));
                
                monServAuto.ajouterAutorisationTemp(matricule, idZone, dateDebut, dateFin);
            }
            else //ajout d'une autorisation permanente
            {
                int hrsDebut=Integer.parseInt(tabHrsDebut[0]+tabHrsDebut[1]);
                int hrsFin=Integer.parseInt(tabHrsFin[0]+tabHrsFin[1]);
                monServAuto.ajouterAutorisationPerm(matricule, idZone, hrsDebut, hrsFin);
            }
           
        }catch(NumberFormatException e){
            System.out.println("Veuillez renseigner les champs d'heures");
        } catch (AutorisationExistante ex) {
            System.out.println(ex.raison);
        }
        //ICIDJGBFHUEJSDGHSDHFGJH
        /*
        try {
            monServAuth.ajouterCollaborateurPerm(matricule, nomUsr, prenomUsr, photoUsr, pwdUsr);
            Utilisateur newUsr = new Utilisateur(matricule, nomUsr, prenomUsr, photoUsr);
            UserTableModel modelCollabPerm = (UserTableModel) jTableCollab.getModel();
            modelCollabPerm.add(newUsr);
        } catch (UtilisateurExistant ex){
            Logger.getLogger(FenGestionRespZone.class.getName()).log(Level.SEVERE, null, ex);
        }
*/
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jTablePermMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePermMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePermMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private org.jdesktop.swingx.JXDatePicker jDateDebut;
    private org.jdesktop.swingx.JXDatePicker jDateFin;
    private javax.swing.JFormattedTextField jHrsDebut;
    private javax.swing.JFormattedTextField jHrsFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMatriculeModif;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePerm;
    private javax.swing.JTable jTableTemp;
    private javax.swing.JTextField jTextFieldMatriculeAjout;
    private javax.swing.JTextField jTextFieldNomModif;
    private javax.swing.JTextField jTextFieldPhotoModif;
    private javax.swing.JTextField jTextFieldPrenomModif;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
}
