/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MachineEmpreinte;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import modEntreesSortiesZones.EmpreinteInconnue;
import modEntreesSortiesZones.ServiceEmpreinte;

/**
 *
 * @author Romain
 */
public class FenModifEmpreinte extends javax.swing.JFrame {

    private ServiceEmpreinte mServEmp;
    private String mMatriculePerm;

    /**
     * Creates new form FenGestionEmpPerm
     */
    public FenModifEmpreinte() {
        initComponents();
        
        CardLayout lCardLayout = (CardLayout)(cardsPanel.getLayout());
        lCardLayout.show(cardsPanel, "mainCard");
    }

    public FenModifEmpreinte(ServiceEmpreinte pServEmp, String pMatriculePerm) {
        initComponents();
        this.mServEmp = pServEmp;
        this.mMatriculePerm = pMatriculePerm;
        
        CardLayout lCardLayout = (CardLayout)(cardsPanel.getLayout());
        lCardLayout.show(cardsPanel, "mainCard");
        
        matriculePermLbl.setText(mMatriculePerm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cardsPanel = new javax.swing.JPanel();
        panelModifierEmp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fieldNewEmpreinte = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnModifEmpreinte = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        mainPanelGestionEmp = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        msgMatriculeLbl = new javax.swing.JLabel();
        matriculePermLbl = new javax.swing.JLabel();
        btnDeconnexion = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        BtnModifEmpreinte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Gestion empreinte");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        cardsPanel.setLayout(new java.awt.CardLayout());

        panelModifierEmp.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Modifier votre empreinte");
        panelModifierEmp.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Veuillez entrer votre nouvelle empreinte :");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5);

        fieldNewEmpreinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNewEmpreinteActionPerformed(evt);
            }
        });
        jPanel1.add(fieldNewEmpreinte);

        panelModifierEmp.add(jPanel1, java.awt.BorderLayout.CENTER);

        btnModifEmpreinte.setText("Modifier");
        btnModifEmpreinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifEmpreinteActionPerformed(evt);
            }
        });
        jPanel2.add(btnModifEmpreinte);

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnnuler);

        panelModifierEmp.add(jPanel2, java.awt.BorderLayout.SOUTH);

        cardsPanel.add(panelModifierEmp, "modifCard");

        mainPanelGestionEmp.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        mainPanelGestionEmp.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        msgMatriculeLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        msgMatriculeLbl.setLabelFor(matriculePermLbl);
        msgMatriculeLbl.setText("Collaborateur matricule :");
        jPanel3.add(msgMatriculeLbl);

        matriculePermLbl.setText("matricule");
        jPanel3.add(matriculePermLbl);

        btnDeconnexion.setText("Deconnexion");
        btnDeconnexion.setMaximumSize(new java.awt.Dimension(80, 23));
        btnDeconnexion.setMinimumSize(new java.awt.Dimension(80, 23));
        btnDeconnexion.setPreferredSize(new java.awt.Dimension(80, 23));
        btnDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnexionActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeconnexion);

        mainPanelGestionEmp.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        BtnModifEmpreinte.setText("Modifier votre empreinte");
        BtnModifEmpreinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifEmpreinteActionPerformed(evt);
            }
        });
        jPanel7.add(BtnModifEmpreinte);

        mainPanelGestionEmp.add(jPanel7, java.awt.BorderLayout.CENTER);

        cardsPanel.add(mainPanelGestionEmp, "mainCard");

        getContentPane().add(cardsPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnexionActionPerformed
        //this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        closeFenModif();
    }//GEN-LAST:event_btnDeconnexionActionPerformed

    private void BtnModifEmpreinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifEmpreinteActionPerformed
        CardLayout lCardLayout = (CardLayout)(cardsPanel.getLayout());
        lCardLayout.show(cardsPanel, "modifCard");
    }//GEN-LAST:event_BtnModifEmpreinteActionPerformed

    private void fieldNewEmpreinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNewEmpreinteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNewEmpreinteActionPerformed

    private void btnModifEmpreinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifEmpreinteActionPerformed
        String empreinteModifiee = fieldNewEmpreinte.getText();
        if ((empreinteModifiee != null) && (empreinteModifiee.length() > 0)) {
            //Custom button text
            int confirmationModif = JOptionPane.showConfirmDialog(
                this, 
                "Etes-vous sûr de modifier votre empreinte par celle-ci :\n" + empreinteModifiee,
                "Confirmation empreinte",
                JOptionPane.YES_NO_OPTION);
            if (confirmationModif == JOptionPane.YES_OPTION){
                try {
                    mServEmp.modifierEmpreinte(empreinteModifiee, mMatriculePerm);
                    JOptionPane.showMessageDialog(this,  "Votre nouvelle empreinte a été enregistrée avec succès.\n");
                    CardLayout lCardLayout = (CardLayout)(cardsPanel.getLayout());
                    lCardLayout.show(cardsPanel, "mainCard");
                } catch (EmpreinteInconnue ex) {
                    JOptionPane.showMessageDialog(this, "Erreur, impossible d'enregistrer votre empreinte :\n"
                            + "Vous n'avez pas enregistré d'empreinte",
                            "Erreur collaborateur inconnu",
                            JOptionPane.ERROR_MESSAGE);
                    closeFenModif();
                }
            }
        }
    }//GEN-LAST:event_btnModifEmpreinteActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        CardLayout lCardLayout = (CardLayout)(cardsPanel.getLayout());
        lCardLayout.show(cardsPanel, "mainCard");
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeFenModif();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    
    
    private void closeFenModif(){
        this.setVisible(false);
        dispose();
        FenConnexionCollab.main(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModifEmpreinte;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnDeconnexion;
    private javax.swing.JButton btnModifEmpreinte;
    private javax.swing.JPanel cardsPanel;
    private javax.swing.JTextField fieldNewEmpreinte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel mainPanelGestionEmp;
    private javax.swing.JLabel matriculePermLbl;
    private javax.swing.JLabel msgMatriculeLbl;
    private javax.swing.JPanel panelModifierEmp;
    // End of variables declaration//GEN-END:variables
}
