/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MachineEmpreinte;

import javax.swing.JPanel;

/**
 *
 * @author Romain
 */
public class PanelConnCollabTemp extends JPanel {

    /**
     * Creates new form PanelTest
     */
    public PanelConnCollabTemp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mConCollabPerm = new javax.swing.JLabel();
        mMatUsrLbl = new javax.swing.JLabel();
        mMatUsrInputField = new javax.swing.JTextField();
        mConnexionBtn = new javax.swing.JButton();

        mConCollabPerm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mConCollabPerm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mConCollabPerm.setText("Connexion collaborateur permanent");
        mConCollabPerm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mMatUsrLbl.setText("Matricule utilisateur :");

        mMatUsrInputField.setText("Saisir votre matricule");
        mMatUsrInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMatUsrInputFieldActionPerformed(evt);
            }
        });

        mConnexionBtn.setText("Connexion");
        mConnexionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConnexionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mConCollabPerm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mMatUsrLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mMatUsrInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mConnexionBtn)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mConCollabPerm, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMatUsrLbl)
                    .addComponent(mMatUsrInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mConnexionBtn)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mConnexionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConnexionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mConnexionBtnActionPerformed

    private void mMatUsrInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMatUsrInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mMatUsrInputFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mConCollabPerm;
    private javax.swing.JButton mConnexionBtn;
    private javax.swing.JTextField mMatUsrInputField;
    private javax.swing.JLabel mMatUsrLbl;
    // End of variables declaration//GEN-END:variables
}
