/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MachineEmpreinte;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import modEntreesSortiesZones.ServiceAuthentification;
import modEntreesSortiesZones.UtilisateurInconnu;

/**
 *
 * @author Romain
 */
public class PanelConnCollabTemp extends JPanel {
    
    private final ServiceAuthentification mServAuth;
    /**
     * Creates new form PanelTest
     * @param pServAuth
     */
    public PanelConnCollabTemp(ServiceAuthentification pServAuth) {
        initComponents();
        this.mServAuth = pServAuth;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mConCollabPerm = new javax.swing.JLabel();
        FlowPanelConnInfos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mMatUsrLbl = new javax.swing.JLabel();
        mMatUsrInputField = new javax.swing.JTextField();
        FlowPanelConnBtn = new javax.swing.JPanel();
        mConnexionBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        mConCollabPerm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mConCollabPerm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mConCollabPerm.setText("Connexion collaborateur temporaire");
        mConCollabPerm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(mConCollabPerm, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        mMatUsrLbl.setLabelFor(mMatUsrInputField);
        mMatUsrLbl.setText("Matricule utilisateur :");
        mMatUsrLbl.setPreferredSize(new java.awt.Dimension(80, 14));
        jPanel1.add(mMatUsrLbl);

        mMatUsrInputField.setText("Saisir votre matricule");
        mMatUsrInputField.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel1.add(mMatUsrInputField);

        FlowPanelConnInfos.add(jPanel1);

        add(FlowPanelConnInfos, java.awt.BorderLayout.CENTER);

        mConnexionBtn.setText("Connexion");
        mConnexionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConnexionBtnActionPerformed(evt);
            }
        });
        FlowPanelConnBtn.add(mConnexionBtn);

        add(FlowPanelConnBtn, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void mConnexionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConnexionBtnActionPerformed
        String mMatriculeCollabTemp = mMatUsrInputField.getText();
        try {
            if(mServAuth.verifierAuthentificationMachineEmpreinteCollaborateurTemp(mMatriculeCollabTemp)) {
                this.setVisible(false);
            }             
        } catch (UtilisateurInconnu ex) {
            Logger.getLogger(FenConnexionCollab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mConnexionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FlowPanelConnBtn;
    private javax.swing.JPanel FlowPanelConnInfos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mConCollabPerm;
    private javax.swing.JButton mConnexionBtn;
    private javax.swing.JTextField mMatUsrInputField;
    private javax.swing.JLabel mMatUsrLbl;
    // End of variables declaration//GEN-END:variables
}
