/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MachineEmpreinte;

import javax.swing.JPanel;

/**
 *
 * @author Romain
 */
public class PanelConnCollabPerm extends JPanel {

    /**
     * Creates new form PanelTest
     */
    public PanelConnCollabPerm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mConCollabPerm = new javax.swing.JLabel();
        mConnexionBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        mMatUsrLbl = new javax.swing.JLabel();
        mMatUsrInputField = new javax.swing.JTextField();
        mPwdLbl = new javax.swing.JLabel();
        mPwdField = new javax.swing.JPasswordField();

        setLayout(new java.awt.BorderLayout());

        mConCollabPerm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mConCollabPerm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mConCollabPerm.setText("Connexion collaborateur permanent");
        mConCollabPerm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(mConCollabPerm, java.awt.BorderLayout.NORTH);

        mConnexionBtn.setText("Connexion");
        mConnexionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConnexionBtnActionPerformed(evt);
            }
        });
        add(mConnexionBtn, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        mMatUsrLbl.setLabelFor(mMatUsrInputField);
        mMatUsrLbl.setText("Matricule utilisateur :");
        jPanel1.add(mMatUsrLbl);

        mMatUsrInputField.setText("Saisir votre matricule");
        mMatUsrInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMatUsrInputFieldActionPerformed(evt);
            }
        });
        jPanel1.add(mMatUsrInputField);

        mPwdLbl.setLabelFor(mPwdField);
        mPwdLbl.setText("Mot de passe :");
        jPanel1.add(mPwdLbl);

        mPwdField.setText("jPasswordField1");
        mPwdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPwdFieldActionPerformed(evt);
            }
        });
        jPanel1.add(mPwdField);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void mPwdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPwdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPwdFieldActionPerformed

    private void mConnexionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConnexionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mConnexionBtnActionPerformed

    private void mMatUsrInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMatUsrInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mMatUsrInputFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mConCollabPerm;
    private javax.swing.JButton mConnexionBtn;
    private javax.swing.JTextField mMatUsrInputField;
    private javax.swing.JLabel mMatUsrLbl;
    private javax.swing.JPasswordField mPwdField;
    private javax.swing.JLabel mPwdLbl;
    // End of variables declaration//GEN-END:variables
}
